# Generated by Django 5.0.3 on 2024-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0004_remove_abadi_shhahr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakhsh',
            name='ostan',
        ),
        migrations.RemoveField(
            model_name='bakhsh',
            name='shahrestan',
        ),
        migrations.RemoveField(
            model_name='dehestan',
            name='bakhsh',
        ),
        migrations.RemoveField(
            model_name='shahr',
            name='bakhsh',
        ),
        migrations.RemoveField(
            model_name='dehestan',
            name='ostan',
        ),
        migrations.RemoveField(
            model_name='dehestan',
            name='shahrestan',
        ),
        migrations.AlterField(
            model_name='shahr',
            name='amar_code',
            field=models.BigIntegerField(verbose_name='Amar Code'),
        ),
        migrations.AlterField(
            model_name='shahr',
            name='shahr_type',
            field=models.BigIntegerField(verbose_name='Shahr Type'),
        ),
        migrations.DeleteModel(
            name='Abadi',
        ),
        migrations.DeleteModel(
            name='Bakhsh',
        ),
        migrations.DeleteModel(
            name='Dehestan',
        ),
    ]
