# Generated by Django 5.0.3 on 2024-06-18 17:55

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_code_alter_user_avatar_alter_user_is_active_and_more'),
        ('iranian_cities', '0004_remove_abadi_shhahr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceAndCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', iranian_cities.fields.ShahrField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.shahr')),
                ('province', iranian_cities.fields.OstanField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.ostan')),
            ],
        ),
    ]
